#!/bin/bash

#!/bin/bash

distribution=`lsb_release -i |gawk '{print $3}'`
distribution_release=`lsb_release -r |gawk '{print $2}'`

current_system="$distribution"_"$distribution_release"

if [[ "$current_system" == "Ubuntu_10.04" ]]; then
        libs2intercept=( "/lib/libc.so.6" "/lib/libpthread.so.0" "/lib/tls/i686/cmov/libpthread.so.0" "/lib/tls/i686/cmov/libc.so.6" )
elif [[ "$current_system" == "Ubuntu_10.10" ]]; then
        libs2intercept=( "/lib/libc.so.6" "/lib/libpthread.so.0" )
elif [[ "$current_system" == "Ubuntu_11.04" ]]; then
        libs2intercept=( "/lib/i386-linux-gnu/libc.so.6" "/lib/i386-linux-gnu/libpthread.so.0" )
else
        echo "[Error] Unknown path for libc and libpthread!!"
        exit 1
fi


for lib in ${libs2intercept[*]}
do
        libPath=$(readlink -f $lib)
        interceptedName=$(basename $libPath)
	
	cd $(dirname $lib)
        sudo ln -vsf ${interceptedName%.intercepted} $(basename $lib)

done

exit 0


cd /lib

sudo ln -sf libpthread-2.12.1.so libpthread.so.0
sudo ln -sf libc-2.12.1.so libc.so.6


libPath=$(readlink libpthread.so.0)
if [ "$libPath" = "libpthread-2.12.1.so" ]
then
	echo "[OK] $libPath is replaced"
else
	echo "[ERROR] $libPath is not replaced"
fi


libPath=$(readlink libc.so.6)
if [ "$libPath" = "libc-2.12.1.so" ]
then
	echo "[OK] $libPath is replaced"
else
	echo "[ERROR] $libPath is not replaced"
fi


loaderPath=$(readlink ld-linux.so.2)
if [ "$loaderPath" = "ld-2.12.1.so.intercepted" ]
then
        echo "[OK] $loaderPath is replaced"
else
        echo "[ERROR] $loaderPath is not replaced"
fi

