sources = lwip_debug.c  lwip_level.c  lwip_notifier.c  lwip_redirectHelper.c \
	  lwip_utils.c lwip_in_utils.c lwip_trackOpen.c \
	  strmap.c  lwip_bufferManager.c  ac.c
include_dirs = ../include/common

include ../common.mk

